onboarding = false

[ui]
status_indicators = "symbols"
show_agent_labels_on_pane_borders = false
mouse_capture = true
copy_on_select = true

[ui.toast]
delivery = "system"

[theme]
name = "rose-pine"
auto_switch = false
